image: python:3.8

pages:
  script:
    - pip install -r requirements.txt
    - pip install jupyter-book
    - jupyter-book build -v book
  artifacts:
    paths:
      - book/_build/html
  only:
    - master
