name: machine_learning_for_climate_and_energy

channels:
  - pyviz
  - conda-forge
  - defaults

dependencies:
  - bokeh>=2.2.3
  - holoviews>=1.14.9
  - hvplot
  - matplotlib
  - netcdf4==1.5.6
  - numpy
  - pandas>=1.2.4
  - panel>=0.10.3
  - python>=3.8
  - rise
  - scipy
  - scikit-learn>=1.0
  - xarray
